VER COUNTS NAS TABELAS = DE ORIGEM PARA VER COMO ESTÃO E VER TAMBÉM SE TEM SCRIPTS PARA MUDANÇA DE ESTRUTURAS.
ACIMA DE 10.000.000 = FICAR ATENTO COM OS INDICES POIS ACIMA DISSO TEM QUE REMOVER E DEPOIS RECRIAR .
FAZER COUNT NAS TABELAS.

GERAR PARA TABELAS PEQUENAS SE FOR O CASO PUBLICAÇÃO MANUAL DE DADO, ASSIM FICA MAIS RAPIDO. LEMBRAR DE FAZER RAPIDO PARA NÃO IMPACTAR, OU COISA TEM QUE VER O AMBIENTE
SE É PRODUÇÃO, HOMOLOGAÇÃO E OUTROS.  NO NOSSO CASO AQUI VAI SER NA HOMOLOGAÇÃO.

OS SCRIPTS ABAIXO ESTÃO NAS MAQUINAS NA PASTA MAINCONTROLM.

/home/dwpublic/dwpub/MAINCONTROLM/ENTRADA.SH

nohup /home/dwpublic/dwpub/MAINCONTROLM/INSERT.SH CONVENIOS WD_TMAD_TERMO_ADITIVO   TODA TODA WD_TMAD_TERMO_ADITIVO     DBL_DWDES035 DWDES035 > insert_WD_TMAD_TERMO_ADITIVO.log &
nohup /home/dwpublic/dwpub/MAINCONTROLM/INSERT.SH CONVENIOS WD_TMAD_SIT_ENVIO_SIAFI      TODA TODA WD_TMAD_SIT_ENVIO_SIAFI      DBL_DWDES035 DWDES035 > insert_WD_TMAD_SIT_ENVIO_SIAFI.log &

comando jobs para conferir se não tem nada em atividade na hora, ou seja executando tudo.
e os counts.
select count(*) from CONVENIOS.WD_TMAD_SIT_ENVIO_SIAFI;
