-- LEMBRAR RONALDO DE VERIFICAR JOB SOBRE TRUNCAR TABELA NO PDW03
-- LEMBRAR ANDRÉ E RONALDO SOBRE COLETA DE ESTATÍSTICAS NO SINESP E VERIFICAÇÃO NO VIEWPOINT
-- VERIFICAR QUAL TPT ESTÁ SENDO UTILIZADO PELO POWER CENTER.


--================================================================================================================
REVER RELATÓRIOS DE PUBLICACAO PARA OWNER IRPF para usuários que não estão chegando. -- ver com ronaldo.
INSTALAR DEVELOPER ORACLE ATUAL NOS ENTREPOSTOS WINDOWS
FAZER DIÁRIO IGUAL SÃO PAULO NO BIPRO001






