--CPU POR SEMANA PARA GERAR MAPA DE CALOR POR ANDRÉ.

lock row for access 
SELECT HORA, 
SUM(CASE WHEN SEMANA = 1 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS DOMINGO,
SUM(CASE WHEN SEMANA = 2 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS SEGUNDA,
SUM(CASE WHEN SEMANA = 3 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS TERÇA,
SUM(CASE WHEN SEMANA = 4 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS QUARTA,
SUM(CASE WHEN SEMANA = 5 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS QUINTA,
SUM(CASE WHEN SEMANA = 6 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS SEXTA,
SUM(CASE WHEN SEMANA = 7 THEN  TOTAL_CPU_USAGE ELSE 0 END) AS SABADO
from (select
TD_DAY_OF_WEEK(thedate) as SEMANA,
(EXTRACT(HOUR FROM (thetime (format '99:99:99')) )) as HORA,
((sum(CPUUExec)) / (sum(CPUIoWait+CPUUExec+CPUUServ+CPUIdle)) ) *100 as CPU_USR,
((sum(CPUUServ)) / (sum(CPUIoWait+CPUUExec+CPUUServ+CPUIdle)) ) *100 as CPU_SYS,
((sum(CPUIoWait)) / (sum(CPUIoWait+CPUUExec+CPUUServ+CPUIdle)) ) *100 as CPU_WIO,
((sum(CPUIdle)) / (sum(CPUIoWait+CPUUExec+CPUUServ+CPUIdle)) ) *100 as CPU_IDLE,
(SUM(CPUUServ+CPUUExec)) / (SUM(CPUIoWait+CPUUExec+CPUUServ+CPUIdle) )* 100  as TOTAL_CPU_USAGE,
AVG((CPUUServ+CPUUExec)  / (CPUUServ+CPUUExec+CPUIOWait+CPUIdle) * 100) (NAMED "AvgBusy%", FORMAT '9999.99') -- okaba
from dbc.resusagespma
-- where thedate (format 'DD/MM/YYYY') >= '01/07/2018' 
where thedate (format 'DD/MM/YYYY') between '07/12/2018'  AND '31/12/2018' 
and  vproc1 NE 0
GROUP BY 1,2) ACUM
GROUP BY HORA
ORDER BY 1;
