RUN ALWAYS ENTRADA.SH BEFORE EVERYTHING ELSE
LOOK INTO THE PATH OF THE MACHINE

~/MAINCONTROLM/ENTRADA.SH

SELECT 'nohup /home/dwpublic/dwpub/MAINCONTROLM/INSERT.SH ' || owner || ' ' || table_name || ' TODA TODA ' || TABLE_NAME || ' DBL_DWCRG36 > /home/dwpublic/dwpub/' || owner || '/' || table_name || '/insert' || TABLE_NAME || '.nohup &'
FROM dba_tables where owner = 'FINANCPAG'
AND TABLE_NAME IN ('WD_ANO', 
'WD_BANCO',
'WD_CENTRO_CUSTO',
'WD_COMPROMISSO',
'WD_DEDUCAO_ENCARGO',
'WD_DIA',
'WD_DOC_HABIL',
'WD_ENTIDADE',
'WD_ESFERA_ADMIN_UG',
'WD_GESTAO',
'WD_IG_CREDORA',
'WD_IG_NAO_CREDORA',
'WD_INST_EXTERNA',
'WD_LOCALIDADE',
'WD_MES',
'WD_MOEDA',
'WD_MUNICIPIO',
'WD_ORGAO',
'WD_PAIS',
'WD_PESSOA_FISICA',
'WD_PESSOA_JURIDICA',
'WD_SITUACAO_ITEM_CC',
'WD_TP_ADMINISTRACAO',
'WD_TP_DOC_HABIL',
'WD_UG',
'WD_UTILIZACAO_SIAFI',
'WF_COMPROMISSO',
'WF_DEDUCAO_ENCARGO',
'WF_DOC_HABIL');

==================================
RUN THE SCRIPT PUBLICACAO.SQL TO ENSURE THAT THE PUBLICATION WAS MADE.



